#!/usr/bin/env node
/**
 * Regenerates the hiscores content and opens a draft PR with it. A human verifies
 * the spelling and merges — this never merges, publishes, or touches main.
 *
 *   node scripts/codegen-content-pr.ts         update, gate, draft PR
 *   node scripts/codegen-content-pr.ts --dry   show the diff, change no git state
 *
 * Requires `pnpm build` first, and an authenticated `gh` (GH_TOKEN in CI).
 */
import { execFileSync } from 'node:child_process';
import { fileURLToPath } from 'node:url';
/* eslint-disable-next-line import/extensions -- Node strips types and needs the real path */
import { keyOf, regen } from './regen-content.ts';

const root = fileURLToPath(new URL('..', import.meta.url));
const run = (file: string, args: string[]): void => {
  execFileSync(file, args, { cwd: root, stdio: 'inherit' });
};
/** execFileSync picks its Buffer overload unless encoding is the literal type. */
const READ = { cwd: root, encoding: 'utf8' } as const;
const read = (file: string, args: string[]): string =>
  execFileSync(file, args, READ);
const bin = (name: string): string => `${root}node_modules/.bin/${name}`;

/** The only paths codegen is allowed to change in a PR. */
const GENERATED_FILES: string[] = ['src/utils/generated', 'README.md'];

/**
 * Same gate CI runs, so a red PR is never filed.
 *
 * ponytail: mirrors main.yml's tool list by hand; add lint:check/format:check
 * scripts to package.json if a third caller ever needs the same list.
 */
const GATE: [string, string[]][] = [
  [
    bin('prettier'),
    ['--check', '{src,__tests__,scripts}/**/*.ts', 'README.md']
  ],
  [bin('eslint'), ['{src,__tests__,scripts}/**/*.ts']],
  [bin('tsc'), []],
  [bin('tsc'), ['-p', 'tsconfig.scripts.json']],
  [bin('vitest'), ['run']]
];

export const prBody = (title: string, notes: readonly string[]): string =>
  `Automated hiscores content update: ${title}

${
  notes.length
    ? `Verify before merging:\n${notes.map((note) => `- ${note}`).join('\n')}\n`
    : ''
}
- [ ] Spelling matches the in-game hiscores page — a typo becomes permanent public API
- [ ] Keys read naturally against src/utils/generated/
- [ ] README boss table rows are correct
- [ ] Merge as a minor release

The lint/build/test gate ran in the job that opened this PR. A pull_request workflow
will not run on it — GitHub does not trigger workflows for PRs opened with
GITHUB_TOKEN — so treat that gate as the CI result.

Generated by \`scripts/codegen-content-pr.ts\` from the live hiscores endpoint.`;

export async function codegen({
  dry = false
}: {
  dry?: boolean;
} = {}): Promise<void> {
  const { addedNames, notes, stale } = await regen();

  if (!stale) {
    console.log(
      'nothing to do — generated content already matches the hiscores'
    );
    return;
  }

  const title = addedNames.length
    ? `feat: add ${addedNames.join(', ')}`
    : 'chore: regenerate hiscores content';
  const addedKeys = addedNames.map(keyOf).join('-').slice(0, 60);
  const branch = `content/add-${addedKeys || 'regen'}`;

  if (dry) {
    console.log(`\nbranch: ${branch}\ntitle:  ${title}\n`);
    notes.forEach((note) => console.log(`note: ${note}`));
    console.log('\n--- diff ---');
    // --intent-to-add so generated files show in the diff before their first commit.
    run('git', ['add', '-N', '--', ...GENERATED_FILES]);
    run('git', ['--no-pager', 'diff', '--', ...GENERATED_FILES]);
    console.log('\n--- PR body ---\n');
    console.log(prBody(title, notes));
    return;
  }

  GATE.forEach(([file, args]) => run(file, args));

  run('git', ['switch', '-C', branch]);
  run('git', ['add', ...GENERATED_FILES]);
  run('git', ['commit', '-m', title]);
  // The branch is regenerated from the default branch on every run, so a second
  // dispatch has to replace whatever the first one pushed.
  run('git', ['push', '--force', '-u', 'origin', 'HEAD']);

  const open = read('gh', [
    'pr',
    'list',
    '--head',
    branch,
    '--state',
    'open',
    '--json',
    'number',
    '--jq',
    'length'
  ]);
  if (open.trim() === '0') {
    run('gh', [
      'pr',
      'create',
      '--draft',
      '--title',
      title,
      '--body',
      prBody(title, notes)
    ]);
  } else {
    console.log(`draft PR for ${branch} is already open — pushed the update`);
  }
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  await codegen({ dry: process.argv.includes('--dry') });
}
