#!/usr/bin/env node
/**
 * Regenerates the hiscores-derived content (`src/utils/generated/*.ts`) and the
 * README boss table. Run `pnpm build` first — the shipped constants are read
 * through `lib/` so the script sees exactly what ships.
 *
 *   node scripts/regen-content.ts           write
 *   node scripts/regen-content.ts --check   report drift, write nothing, exit 1 if stale
 *
 * ponytail: the fixed activity block (points, Bounty Hunter, clue scrolls, minigames)
 * has no key<->display rule either, but its twenty names are a closed set, so a
 * table of the thirteen that the rule cannot name makes it derivable too. A new
 * name the table does not cover fails the run rather than guessing a public key.
 */
import { readFile, writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import prettier from 'prettier';

/** The built package, typed from the source it was built from. */
type Lib = typeof import('../src/index.js');
type Stats = Awaited<ReturnType<Lib['getOfficialStats']>>;
/** A generated entry: its key, then the hiscores display name. */
type Entry = readonly [key: string, name: string];
type Shipped = Record<string, string>;

const root = fileURLToPath(new URL('..', import.meta.url));
const at = (file: string): string => root + file;
const LIB = '../lib/index.js';

/** Reference RSNs; both must report the same content list or we refuse to write. */
const REFERENCE_RSN = ['B0aty', 'Lynx Titan'];

/**
 * Display names the naming rule cannot reproduce: the legacy keys the package
 * already ships. A new name that lands here fails the run, because picking a
 * public key is a human decision.
 */
const KEY_OVERRIDES: Shipped = {
  'Barrows Chests': 'barrows',
  'Bounty Hunter - Hunter': 'hunterBHV2',
  'Bounty Hunter - Rogue': 'rogueBHV2',
  'Bounty Hunter (Legacy) - Hunter': 'hunterBH',
  'Bounty Hunter (Legacy) - Rogue': 'rogueBH',
  'Clue Scrolls (all)': 'allClues',
  'Clue Scrolls (beginner)': 'beginnerClues',
  'Clue Scrolls (easy)': 'easyClues',
  'Clue Scrolls (medium)': 'mediumClues',
  'Clue Scrolls (hard)': 'hardClues',
  'Clue Scrolls (elite)': 'eliteClues',
  'Clue Scrolls (master)': 'masterClues',
  'LMS - Rank': 'lastManStanding',
  'PvP Arena - Rank': 'pvpArena'
};

const HEADER =
  '// @generated by scripts/regen-content.ts — do not edit by hand.\n';

const renderList = (keys: readonly string[]): string =>
  keys.map((key) => `  ${JSON.stringify(key)},`).join('\n');
const renderMap = (entries: readonly Entry[]): string =>
  entries.map(([key, name]) => `  ${key}: ${JSON.stringify(name)},`).join('\n');

/**
 * Turns a hiscores display name into its key: strip apostrophes, drop a leading
 * article, then camelCase on word boundaries while keeping capitals inside a word
 * (TzKal-Zuk -> tzKalZuk, Phosani's Nightmare -> phosanisNightmare).
 */
export const keygen = (name: string): string =>
  name
    .replace(/['’]/g, '')
    .replace(/^The\s+/i, '')
    .split(/[^a-zA-Z0-9]+/)
    .filter(Boolean)
    .map((word, i) =>
      i === 0
        ? word[0].toLowerCase() + word.slice(1)
        : word[0].toUpperCase() + word.slice(1)
    )
    .join('');

export const keyOf = (name: string): string =>
  Object.hasOwn(KEY_OVERRIDES, name) ? KEY_OVERRIDES[name] : keygen(name);

const renderSkills = (
  entries: readonly Entry[]
): string => `${HEADER}// Skills and their hiscores display names.
export const SKILLS = [
${renderList(entries.map(([key]) => key))}
] as const;
export type SkillName = (typeof SKILLS)[number];

export type FormattedSkillNames = {
  [key in SkillName]: string;
};

export const FORMATTED_SKILL_NAMES: FormattedSkillNames = {
${renderMap(entries)}
};
`;

export const renderBosses = (
  entries: readonly Entry[]
): string => `${HEADER}// Bosses and their hiscores display names, in hiscores order.
export const BOSSES = [
${renderList(entries.map(([key]) => key))}
] as const;
export type Boss = (typeof BOSSES)[number];

export type FormattedBossNames = {
  [key in Boss]: string;
};

export const FORMATTED_BOSS_NAMES: FormattedBossNames = {
${renderMap(entries)}
};
`;

export const renderFixedActivities = (
  entries: readonly Entry[]
): string => `${HEADER}// Points, Bounty Hunter, clue scrolls and minigames, in hiscores order.
// ACTIVITIES is built from this list, so its order is the hiscores table index.
export const FIXED_ACTIVITIES = [
${renderList(entries.map(([key]) => key))}
] as const;
`;

const TABLE_MARKERS = /(<!-- begin:bosses -->\n)[\s\S]*?(<!-- end:bosses -->)/;

export const renderBossesTable = (entries: readonly Entry[]): string =>
  [
    '| Boss Name | Param |',
    '| --- | :---: |',
    ...entries.map(([key, name]) => `| ${name} | \`${key}\` |`)
  ].join('\n');

const renderReadme = (markdown: string, entries: readonly Entry[]): string => {
  if (!TABLE_MARKERS.test(markdown)) {
    throw new Error('README.md is missing the boss table markers');
  }
  // Function replacer: display names are endpoint data, not a replacement pattern.
  return markdown.replace(
    TABLE_MARKERS,
    (_, begin, end) => `${begin}${renderBossesTable(entries)}\n${end}`
  );
};

const entry = (name: string): Entry => [keyOf(name), name];

const fetchLiveContent = async (): Promise<{
  lib: Lib;
  fixed: Entry[];
  bosses: Entry[];
  skills: Entry[];
}> => {
  const lib: Lib = await import(LIB);
  const [a, b] = await Promise.all(
    REFERENCE_RSN.map((rsn) => lib.getOfficialStats(rsn))
  );
  const names = (response: Stats): string[] => [
    ...response.skills.map((s) => s.name),
    ...response.activities.map((activity) => activity.name)
  ];
  const liveNames = names(a);
  if (liveNames.join('|') !== names(b).join('|')) {
    throw new Error(
      `${REFERENCE_RSN.join(' and ')} disagree on the content list`
    );
  }

  const shippedBosses = Object.entries(lib.FORMATTED_BOSS_NAMES);
  const firstBoss = liveNames.findIndex((name) =>
    shippedBosses.some(([, display]) => display === name)
  );
  if (firstBoss < 0) {
    throw new Error('no known boss in the hiscores activity list');
  }

  // Everything before the first known boss is the fixed block: points, Bounty
  // Hunter, clue scrolls, minigames. It is generated from the live order, so the
  // table numbers line up by construction.
  const liveFixed = a.activities.slice(0, firstBoss - a.skills.length);
  const fixed = liveFixed.map(({ name }) => entry(name));

  return {
    lib,
    fixed,
    bosses: a.activities
      .slice(firstBoss - a.skills.length)
      .map(({ name }) => entry(name)),
    skills: a.skills.map(({ name }) => entry(name))
  };
};

/** Fails loudly when the live hiscores and the shipped constants disagree. */
export const validate = (
  label: string,
  entries: readonly Entry[],
  shipped: Shipped
): void => {
  const stubborn = Object.entries(shipped).filter(
    ([key, display]) => keyOf(display) !== key
  );
  if (stubborn.length) {
    throw new Error(
      `${label}: keygen no longer reproduces ${stubborn
        .map(
          ([key, display]) => `${display} -> ${keyOf(display)} (key is ${key})`
        )
        .join(', ')}`
    );
  }

  const gone = Object.keys(shipped).filter(
    (key) => !entries.some(([liveKey]) => liveKey === key)
  );
  if (gone.length) {
    throw new Error(
      `${label}: hiscores dropped ${gone.join(', ')} — removing content is a human decision`
    );
  }

  const keys = entries.map(([key]) => key);
  const duplicates = keys.filter((key, i) => keys.indexOf(key) !== i);
  if (duplicates.length) {
    throw new Error(`${label}: duplicate keys ${duplicates.join(', ')}`);
  }
};

const added = (entries: readonly Entry[], shipped: Shipped): string[] =>
  entries
    .filter(([key]) => !Object.hasOwn(shipped, key))
    .map(([, name]) => name);

/**
 * Fetches the live content and renders the files it owns.
 *
 * @returns Added names, and whether the working tree differs from them.
 */
export async function regen({
  check = false
}: { check?: boolean } = {}): Promise<{
  addedNames: string[];
  notes: string[];
  stale: boolean;
}> {
  const { lib, skills, bosses, fixed } = await fetchLiveContent();
  validate('skills', skills, lib.FORMATTED_SKILL_NAMES);
  validate('bosses', bosses, lib.FORMATTED_BOSS_NAMES);
  // One namespace, one uniqueness rule: ACTIVITIES is what indexOf resolves against.
  validate('activities', [...fixed, ...bosses], {});

  // Removing content is a human decision, and the fixed block is regenerated, so
  // a name the hiscores dropped has to be caught here rather than diffed away.
  const shippedFixed: readonly string[] = lib.ACTIVITIES.slice(
    0,
    lib.ACTIVITIES.length - lib.BOSSES.length
  );
  const dropped = shippedFixed.filter(
    (key) => !fixed.some(([liveKey]) => liveKey === key)
  );
  if (dropped.length) {
    throw new Error(
      `hiscores dropped ${dropped.join(', ')} — removing content is a human decision`
    );
  }

  const addedNames = [
    ...added(skills, lib.FORMATTED_SKILL_NAMES),
    ...added(bosses, lib.FORMATTED_BOSS_NAMES),
    ...fixed
      .filter(([key]) => !shippedFixed.includes(key))
      .map(([, name]) => name)
  ];

  const notes: string[] = [];
  const lastBoss = bosses.at(-1);
  // A name appended after the last known boss is either brand new content or a
  // minigame the hiscores list now ends with — the endpoint does not say which.
  if (lastBoss && !Object.hasOwn(lib.FORMATTED_BOSS_NAMES, lastBoss[0])) {
    notes.push(
      `"${lastBoss[1]}" was appended to the end of the hiscores list — confirm it is a boss and not a minigame`
    );
  }

  // The key stayed put but the name the user sees changed: a public display name.
  const shippedNames: Shipped = {
    ...lib.FORMATTED_SKILL_NAMES,
    ...lib.FORMATTED_BOSS_NAMES
  };
  [...skills, ...bosses].forEach(([key, name]) => {
    if (shippedNames[key] && shippedNames[key] !== name) {
      notes.push(
        `"${shippedNames[key]}" is now "${name}" in the hiscores — a public display name changed`
      );
    }
  });

  const targets: [string, string][] = [
    ['src/utils/generated/skills.ts', renderSkills(skills)],
    ['src/utils/generated/bosses.ts', renderBosses(bosses)],
    ['src/utils/generated/activities.ts', renderFixedActivities(fixed)],
    ['README.md', renderReadme(await readFile(at('README.md'), 'utf8'), bosses)]
  ];

  let stale = false;
  for (const [file, text] of targets) {
    const options = (await prettier.resolveConfig(at(file))) ?? {};
    const rendered = await prettier.format(text, {
      ...options,
      filepath: at(file)
    });
    if (rendered === (await readFile(at(file), 'utf8'))) continue;
    stale = true;
    if (check) continue;
    await writeFile(at(file), rendered);
    console.log(`updated ${file}`);
  }

  return { addedNames, notes, stale };
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  const check = process.argv.includes('--check');
  const { addedNames, notes, stale } = await regen({ check });
  if (addedNames.length) {
    console.log(`new hiscores content: ${addedNames.join(', ')}`);
  }
  notes.forEach((note) => console.log(`note: ${note}`));
  if (!stale) {
    console.log('generated content is up to date');
  } else if (check) {
    console.error('generated content is stale — run without --check to update');
    process.exit(1);
  }
}
