#!/usr/bin/env node
/**
 * Regenerates the hiscores-derived content (`src/utils/generated/*.ts`) and the
 * README boss table. Run `pnpm build` first — the shipped constants are read
 * through `lib/` so the script sees exactly what ships.
 *
 *   node scripts/regen-content.mjs           write
 *   node scripts/regen-content.mjs --check   report drift, write nothing, exit 1 if stale
 *
 * ponytail: only skills and bosses are derived. The fixed activity block (points,
 * Bounty Hunter, clue scrolls, minigames) has no key<->display rule, so it stays
 * hand-authored in constants.ts; a new entry there is still a manual edit.
 */
import { readFile, writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import prettier from 'prettier';

const root = fileURLToPath(new URL('..', import.meta.url));
const at = (file) => root + file;
const LIB = '../lib/index.js';

/** Reference RSNs; both must report the same content list or we refuse to write. */
const REFERENCE_RSN = ['B0aty', 'Lynx Titan'];

/** Words dropped from a display name because they are not part of the key. */
const KEY_OVERRIDES = { 'Barrows Chests': 'barrows' };

const HEADER =
  '// @generated by scripts/regen-content.mjs — do not edit by hand.\n';

const lit = (value) =>
  value.includes("'") ? JSON.stringify(value) : `'${value}'`;
const renderList = (keys) => keys.map((key) => `  ${lit(key)},`).join('\n');
const renderMap = (entries) =>
  entries.map(([key, name]) => `  ${key}: ${lit(name)},`).join('\n');

/**
 * Turns a hiscores display name into its key: strip apostrophes, drop a leading
 * article, then camelCase on word boundaries while keeping capitals inside a word
 * (TzKal-Zuk -> tzKalZuk, Phosani's Nightmare -> phosanisNightmare).
 */
export const keygen = (name) =>
  name
    .replace(/['’]/g, '')
    .replace(/^The\s+/i, '')
    .split(/[^a-zA-Z0-9]+/)
    .filter(Boolean)
    .map((word, i) =>
      i === 0
        ? word[0].toLowerCase() + word.slice(1)
        : word[0].toUpperCase() + word.slice(1)
    )
    .join('');

export const keyOf = (name) => KEY_OVERRIDES[name] ?? keygen(name);

export const renderSkills = (
  entries
) => `${HEADER}// Skills and their hiscores display names.
export const SKILLS = [
${renderList(entries.map(([key]) => key))}
] as const;
export type SkillName = (typeof SKILLS)[number];

export type FormattedSkillNames = {
  [key in SkillName]: string;
};

export const FORMATTED_SKILL_NAMES: FormattedSkillNames = {
${renderMap(entries)}
};
`;

export const renderBosses = (
  entries
) => `${HEADER}// Bosses and their hiscores display names, in hiscores order.
export const BOSSES = [
${renderList(entries.map(([key]) => key))}
] as const;
export type Boss = (typeof BOSSES)[number];

export type FormattedBossNames = {
  [key in Boss]: string;
};

export const FORMATTED_BOSS_NAMES: FormattedBossNames = {
${renderMap(entries)}
};
`;

const TABLE_MARKERS = /(<!-- begin:bosses -->\n)[\s\S]*?(<!-- end:bosses -->)/;

export const renderBossesTable = (entries) =>
  [
    '| Boss Name | Param |',
    '| --- | :---: |',
    ...entries.map(([key, name]) => `| ${name} | \`${key}\` |`)
  ].join('\n');

const renderReadme = (markdown, entries) => {
  if (!TABLE_MARKERS.test(markdown)) {
    throw new Error('README.md is missing the boss table markers');
  }
  return markdown.replace(TABLE_MARKERS, `$1${renderBossesTable(entries)}\n$2`);
};

const fetchLiveContent = async () => {
  const lib = await import(LIB);
  const [a, b] = await Promise.all(
    REFERENCE_RSN.map((rsn) => lib.getOfficialStats(rsn))
  );
  const names = (response) => [
    ...response.skills.map((s) => s.name),
    ...response.activities.map((activity) => activity.name)
  ];
  const [liveNames] = [names(a)];
  if (liveNames.join('|') !== names(b).join('|')) {
    throw new Error(
      `${REFERENCE_RSN.join(' and ')} disagree on the content list`
    );
  }

  const noted = Object.entries(lib.FORMATTED_BOSS_NAMES);
  const firstBoss = liveNames.findIndex((name) =>
    noted.some(([, display]) => display === name)
  );
  if (firstBoss < 0) {
    throw new Error('no known boss in the hiscores activity list');
  }

  return {
    lib,
    skills: a.skills.map(({ name }) => [keyOf(name), name]),
    bosses: a.activities
      .slice(firstBoss - a.skills.length)
      .map(({ name }) => [keyOf(name), name])
  };
};

/** Fails loudly when the live hiscores and the shipped constants disagree. */
const validate = (label, entries, shipped) => {
  const stubborn = Object.entries(shipped).filter(
    ([key, display]) => keyOf(display) !== key
  );
  if (stubborn.length) {
    throw new Error(
      `${label}: keygen no longer reproduces ${stubborn
        .map(([key, display]) => `${display} -> ${key}`)
        .join(', ')}`
    );
  }

  const gone = Object.keys(shipped).filter(
    (key) => !entries.some(([liveKey]) => liveKey === key)
  );
  if (gone.length) {
    throw new Error(
      `${label}: hiscores dropped ${gone.join(', ')} — removing content is a human decision`
    );
  }

  const keys = entries.map(([key]) => key);
  const duplicates = keys.filter((key, i) => keys.indexOf(key) !== i);
  if (duplicates.length) {
    throw new Error(`${label}: duplicate keys ${duplicates.join(', ')}`);
  }
};

const added = (entries, shipped) =>
  entries.filter(([key]) => !(key in shipped)).map(([, name]) => name);

/**
 * Fetches the live content and renders the files it owns.
 *
 * @returns Added names, and whether the working tree differs from them.
 */
export async function regen({ check = false } = {}) {
  const { lib, skills, bosses } = await fetchLiveContent();
  validate('skills', skills, lib.FORMATTED_SKILL_NAMES);
  validate('bosses', bosses, lib.FORMATTED_BOSS_NAMES);

  const addedNames = [
    ...added(skills, lib.FORMATTED_SKILL_NAMES),
    ...added(bosses, lib.FORMATTED_BOSS_NAMES)
  ];

  const notes = [];
  const lastBoss = bosses.at(-1);
  // A name appended after the last known boss is either brand new content or a
  // minigame the hiscores list now ends with — the endpoint does not say which.
  if (lastBoss && !(lastBoss[0] in lib.FORMATTED_BOSS_NAMES)) {
    notes.push(
      `"${lastBoss[1]}" was appended to the end of the hiscores list — confirm it is a boss and not a minigame`
    );
  }

  const targets = [
    ['src/utils/generated/skills.ts', renderSkills(skills)],
    ['src/utils/generated/bosses.ts', renderBosses(bosses)],
    ['README.md', renderReadme(await readFile(at('README.md'), 'utf8'), bosses)]
  ];

  let stale = false;
  for (const [file, text] of targets) {
    const options = await prettier.resolveConfig(at(file));
    const rendered = await prettier.format(text, {
      ...options,
      filepath: at(file)
    });
    if (rendered === (await readFile(at(file), 'utf8'))) continue;
    stale = true;
    if (check) continue;
    await writeFile(at(file), rendered);
    console.log(`updated ${file}`);
  }

  return { addedNames, notes, stale };
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  const check = process.argv.includes('--check');
  const { addedNames, notes, stale } = await regen({ check });
  if (addedNames.length) {
    console.log(`new hiscores content: ${addedNames.join(', ')}`);
  }
  notes.forEach((note) => console.log(`note: ${note}`));
  if (!stale) {
    console.log('generated content is up to date');
  } else if (check) {
    console.error('generated content is stale — run without --check to update');
    process.exit(1);
  }
}
